Updated yaml

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -1,4 +1,5 @@
 # Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
 on:
   push:
     branches: [main, master]
@@ -31,11 +32,15 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: Ensure qpdf on macOS
+      - name: Set up Homebrew (macOS only)
         if: runner.os == 'macOS'
         run: |
-          brew list qpdf || brew install qpdf
-        continue-on-error: true
+          brew update || true
+
+      - name: Install qpdf (macOS only)
+        if: runner.os == 'macOS'
+        run: |
+          brew install qpdf || true
 
       - uses: r-lib/actions/setup-pandoc@v2
 
@@ -45,12 +50,6 @@ jobs:
           http-user-agent: ${{ matrix.config.http-user-agent }}
           use-public-rspm: true
 
-      - name: Debug dependencies on macOS
-        if: runner.os == 'macOS'
-        run: |
-          brew doctor || true
-          brew list || true
-
       - uses: r-lib/actions/setup-r-dependencies@v2
         with:
           extra-packages: any::rcmdcheck
@@ -59,4 +58,4 @@ jobs:
       - uses: r-lib/actions/check-r-package@v2
         with:
           upload-snapshots: true
-          build_args: 'c("--no-manual")' # "--compact-vignettes=gs+qpdf")
+          build_args: 'c("--no-manual")' # "--compact-vignettes=gs+qpdf")'
